#!/bin/sh
echo "your src code file is : " $2
echo "your object file is   : " $1
if [ $# -lt 2 ]; then
echo "==================================="
echo "usage:"
echo "iteadcompile objectfile  xxx.c"
echo "==================================="
else
echo "now building......"
gcc -o $1 $2 $3 $4 $5 $6 $7 $8 $9 -liteadcpp -lstdc++
fi
